CREATE DATABASE COMPANY;

CREATE TABLE EMPLOYEE(EM_ID INT PRIMARY KEY, EM_LASTNAME CHAR(20), EM_FIRSTNAME CHAR(20), EM_POSITION CHAR(20), EM_DEPARTMENT CHAR(20), EM_BRANCH INT, EM_BEGIN DATE, EM_END DATE) 
CREATE TABLE POSITION(PS_POSITION CHAR(20) PRIMARY KEY, PS_SALARY INT);
CREATE TABLE DEPARTMENT(D_DEPARTMENT CHAR(20) PRIMARY KEY, D_BEGIN DATE, D_END DATE);
CREATE TABLE BRANCH(B_ID INT PRIMARY KEY, B_BRANCH CHAR(20), B_CITY CHAR(20), B_STREET CHAR(20), B_HOUSE CHAR(20), B_BEGIN DATE, B_END DATE);
CREATE TABLE M2M_BRANCH_DEPARTMENT(B_ID INT, D_DEPARTMENT CHAR(20), PRIMARY KEY(B_ID, D_DEPARTMENT));
--CREATE TABLE BUDGET(NAME_OF_BRANCH CHAR(20) ,NAME_OF_DEPARTMENT CHAR(20), MONTH_YEAR CHAR(20), BUDGET INT);
--CREATE TABLE CLIENT(SURNAME CHAR(20), NAME CHAR(20), PRIMARY KEY(SURNAME, NAME));
CREATE TABLE EXPENSES(EX_ID INT PRIMARY KEY, EX_NAME CHAR(20), EX_AMOUNT INT, EX_EMPLOYEE INT, EX_DATE DATE);
CREATE TABLE PROFIT(PR_ID INT PRIMARY KEY, PR_NAME CHAR(20), PR_AMOUNT INT, PR_EMPLOYEE INT, PR_DATE DATE);

CREATE TABLE USERS(U_ID INT PRIMARY KEY IDENTITY, U_LOGIN CHAR(20),  U_LASTNAME CHAR(20), U_FIRSTNAME CHAR(20), U_ROLE CHAR(1));
CREATE TABLE PASSWORDS(PA_ID INT PRIMARY KEY, PA_PASSWORD CHAR(20) NOT NULL);

DROP TABLE EMPLOYEE;
DROP TABLE POSITION;
DROP TABLE DEPARTMENT;
DROP TABLE BRANCH;
DROP TABLE M2M_BRANCH_DEPARTMENT;
DROP TABLE EXPENSES;
DROP TABLE PROFIT;

DROP TABLE USERS;
DROP TABLE PASSWORDS;

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_POSITION FOREIGN KEY (EM_POSITION) REFERENCES POSITION(PS_POSITION);
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (EM_DEPARTMENT) REFERENCES DEPARTMENT(D_DEPARTMENT); 
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_BRACH FOREIGN KEY (EM_BRANCH) REFERENCES BRANCH(B_ID);
ALTER TABLE EXPENSES ADD CONSTRAINT FK_EXPENSES_EMPLOYEE FOREIGN KEY (EX_EMPLOYEE) REFERENCES EMPLOYEE(EM_ID);
ALTER TABLE PROFIT ADD CONSTRAINT FK_PROFIT_EMPLOYEE FOREIGN KEY (PR_EMPLOYEE) REFERENCES EMPLOYEE(EM_ID);
ALTER TABLE M2M_BRANCH_DEPARTMENT ADD CONSTRAINT FK_M2M_BRANCH_DEPARTMENT_DEPARTMENT FOREIGN KEY (D_DEPARTMENT) REFERENCES DEPARTMENT(D_DEPARTMENT);
ALTER TABLE M2M_BRANCH_DEPARTMENT ADD CONSTRAINT FK_M2M_BRANCH_DEPARTMENT_BRANCH FOREIGN KEY (B_ID) REFERENCES BRANCH(B_ID);

ALTER TABLE PASSWORDS ADD CONSTRAINT FK_PASSWORDS_USERS FOREIGN KEY (PA_ID) REFERENCES USERS(U_ID);

ALTER TABLE EMPLOYEE DROP FK_EMPLOYEE_POSITION;
ALTER TABLE EMPLOYEE DROP FK_EMPLOYEE_DEPARTMENT;
ALTER TABLE EMPLOYEE DROP FK_EMPLOYEE_BRACH;
ALTER TABLE EXPENSES DROP FK_EXPENSES_EMPLOYEE;
ALTER TABLE PROFIT DROP FK_PROFIT_EMPLOYEE;
ALTER TABLE M2M_BRANCH_DEPARTMENT DROP FK_M2M_BRANCH_DEPARTMENT_DEPARTMENT;
ALTER TABLE M2M_BRANCH_DEPARTMENT DROP FK_M2M_BRANCH_DEPARTMENT_BRANCH;


ALTER TABLE PASSWORDS DROP FK_PASSWORDS_USERS;

SELECT * FROM EMPLOYEE;
SELECT * FROM POSITION;
SELECT * FROM DEPARTMENT;
SELECT * FROM BRANCH;
SELECT * FROM M2M_BRANCH_DEPARTMENT;
SELECT * FROM EXPENSES;
SELECT * FROM PROFIT;

SELECT * FROM USERS;
SELECT * FROM PASSWORDS;

INSERT INTO USERS(U_LOGIN, U_LASTNAME, U_FIRSTNAME, U_ROLE)
VALUES ('Shu Ouma', 'Ouma', 'Shu', 1), 
('Inori Yuzuriha', 'Yuzuriha', 'Inori', 2),
('Haruka Ouma', 'Ouma', 'Haruka', 3);

INSERT INTO PASSWORDS 
VALUES(2, 123),
(3, 123),
(4, 123);

INSERT INTO EMPLOYEE()
VALUES();

INSERT INTO POSITION
VALUES();

INSERT INTO DATEPART
VALUES();

INSERT INTO BRANCH
VALUES();

INSERT INTO M2M_BRANCH_DEPARTMENT
VALUES();

INSERT INTO EXPENSES
VALUES();

INSERT INTO PROFIT
VALUES();


DELETE FROM USERS;
DELETE FROM PASSWORDS;
