CREATE DATABASE COURSE_WORK_SITAIRIS;
USE COURSE_WORK_SITAIRIS;

CREATE TABLE CAR (C_ID INT PRIMARY KEY IDENTITY, T_ID INT, P_ID INT, O_ID INT, S_ID INT, C_MODEL CHAR(20), C_PRICE_PER_DAY INT, C_PHOTO CHAR(30));
CREATE TABLE TRANSMISSION (T_ID INT PRIMARY KEY IDENTITY, T_NAME CHAR(20));
CREATE TABLE PRODUCER (P_ID INT PRIMARY KEY IDENTITY, P_NAME CHAR(20), P_SALE INT);  
CREATE TABLE STATS(S_ID INT PRIMARY KEY IDENTITY, S_STAT INT);
CREATE TABLE OWNERS(O_ID INT PRIMARY KEY IDENTITY, O_ADDRESS CHAR(20));
CREATE TABLE RESERVAYION(R_ID INT PRIMARY KEY IDENTITY, U_ID INT, C_ID INT, T_ID INT, P_ID INT, O_ID INT, S_ID INT, R_DATA_OF_BEGINNING DATE, R_DATA_OF_END DATE, R_PRICE INT);
CREATE TABLE USERS(U_ID INT PRIMARY KEY IDENTITY,U_SURNAME CHAR(20), U_LOGIN CHAR(20), U_TELEPHONE_NUMBER CHAR(20), U_MAIL CHAR(20), U_ROLE INT, U_CERTIFICATE CHAR(20), U_DATE_OF_BIRTH DATE);
CREATE TABLE PASSWORDS(U_LOGIN CHAR(20) PRIMARY KEY, P_PASSWORD CHAR(20));

ALTER TABLE CAR ADD CONSTRAINT FK_CAR_TRANSMISSION FOREIGN KEY (T_ID) REFERENCES TRANSMISSION(T_ID);
ALTER TABLE CAR ADD CONSTRAINT FK_CAR_PRODUCER FOREIGN KEY (P_ID) REFERENCES PRODUCER(P_ID);
ALTER TABLE CAR ADD CONSTRAINT FK_CAR_STATS FOREIGN KEY (S_ID) REFERENCES STATS(S_ID);
ALTER TABLE CAR ADD CONSTRAINT FK_CAR_OWNERS FOREIGN KEY (O_ID) REFERENCES OWNERS(O_ID);
ALTER TABLE RESERVAYION ADD CONSTRAINT FK_RESERVAYION_CAR FOREIGN KEY (C_ID) REFERENCES CAR(C_ID);
ALTER TABLE RESERVAYION ADD CONSTRAINT FK_RESERVAYION_USERS FOREIGN KEY (U_ID) REFERENCES USERS(U_ID);
ALTER TABLE USERS ADD CONSTRAINT FK_USERS_PASSWORDS FOREIGN KEY (U_LOGIN) REFERENCES PASSWORDS(U_LOGIN);

ALTER TABLE CAR DROP FK_CAR_TRANSMISSION;
ALTER TABLE CAR DROP FK_CAR_PRODUCER;
ALTER TABLE CAR DROP FK_CAR_STATS;
ALTER TABLE CAR DROP FK_CAR_OWNERS;
ALTER TABLE RESERVAYION DROP FK_RESERVAYION_CAR;
ALTER TABLE RESERVAYION DROP FK_RESERVAYION_USERS;
ALTER TABLE USERS DROP FK_USERS_PASSWORDS;

SELECT * FROM CAR;
SELECT * FROM TRANSMISSION;
SELECT * FROM PRODUCER;
SELECT * FROM STATS;
SELECT * FROM OWNERS;
SELECT * FROM RESERVAYION;
SELECT * FROM USERS;
SELECT * FROM PASSWORDS;

DROP TABLE CAR;
DROP TABLE TRANSMISSION;
DROP TABLE PRODUCER;
DROP TABLE STATS;
DROP TABLE OWNERS;
DROP TABLE RESERVAYION;
DROP TABLE USERS;
DROP TABLE PASSWORDS;

INSERT INTO CAR
VALUES();

INSERT INTO TRANSMISSION
VALUES(1, "механика"),
(2, "автомат");

INSERT INTO PRODUCER
VALUES(1, "Toyota", 10),
(2, "Mercedes", 10);

INSERT INTO STATS
VALUES(1, 1),
(1, 0);

INSERT INTO OWNERS
VALUES(1, "Минск");

INSERT INTO USERS
VALUES();

INSERT INTO PASSWORDS
VALUES();
