CREATE DATABASE LIBRARY;

CREATE TABLE BOOKS(B_ID INT PRIMARY KEY, B_NAME CHAR(20), B_YEAR SMALLINT, B_QUANTITY SMALLINT);
CREATE TABLE GENRES(G_ID INT PRIMARY KEY, G_NAME CHAR(20));
CREATE TABLE AUTHORS(A_ID INT PRIMARY KEY, A_NAME CHAR(20));
CREATE TABLE SUBSCRIBERS(S_ID INT PRIMARY KEY, S_NAME CHAR(20));
CREATE TABLE SUBSCRIPTIONS(SB_ID INT PRIMARY KEY, SB_SUBSCRIBER INT, SB_BOOK INT, SB_START DATE, SB_END DATE, SB_IS_ACTIVE CHAR(1));
CREATE TABLE M2M_BOOKS_GENRES(B_ID INT, G_ID INT, PRIMARY KEY(B_ID, G_ID));
CREATE TABLE M2M_BOOKS_AUTHORS(B_ID INT, A_ID INT, PRIMARY KEY(B_ID, A_ID));

DROP TABLE BOOKS;
DROP TABLE GENRES;
DROP TABLE AUTHORS;
DROP TABLE SUBSCRIBERS;
DROP TABLE SUBSCRIPTIONS;
DROP TABLE M2M_BOOKS_GENRES;
DROP TABLE M2M_BOOKS_AUTHORS;

ALTER TABLE M2M_BOOKS_GENRES ADD CONSTRAINT FK_M2M_BOOKS_GENRES_GENRES FOREIGN KEY (G_ID) REFERENCES GENRES(G_ID);

INSERT INTO BOOKS
VALUES ();

INSERT INTO GENRES
VALUES ();

INSERT INTO AUTHORS
VALUES ();

INSERT INTO SUBSCRIBERS
VALUES ();

INSERT INTO SUBSCRIPTIONS
VALUES ();

INSERT INTO M2M_BOOKS_GENRES
VALUES ();

INSERT INTO M2M_BOOKS_AUTHORS
VALUES ();
