CREATE DATABASE test_database;

CREATE TABLE FILM (ID_FILM INT IDENTITY PRIMARY KEY, NAME VARCHAR(50), DURATION INT);
CREATE TABLE GENRE (FILM INT NOT NULL, GENRE VARCHAR(50) NOT NULL);
CREATE TABLE SESSION (ID_SESSION INT IDENTITY PRIMARY KEY, HALL INT , DATE DATE, TIME TIME, FILM INT);
CREATE TABLE HALL (ID_HALL INT IDENTITY PRIMARY KEY, NAME VARCHAR(50), RANGSE INT, SEATS INT );
CREATE TABLE SEAT (ID_SEAT INT IDENTITY PRIMARY KEY, HALL INT , RANGE INT , SEAT INT );
CREATE TABLE TICKET(ID_TICKET INT IDENTITY PRIMARY KEY, SESSION INT , SEAT INT , PRICE MONEY);

DROP TABLE FILM;
DROP TABLE GENRE;
DROP TABLE SESSION;
DROP TABLE HALL;
DROP TABLE SEAT;
DROP TABLE TICKET;

ALTER TABLE HALL ADD KOL_SEATS INT;

ALTER TABLE FILM 
ALTER COLUMN DURATION INT NOT NULL;

ALTER TABLE GENRE ADD PRIMARY KEY(FILM, GENRE);
ALTER TABLE SESSION ADD FOREIGN KEY(FILM) REFERENCES FILM(ID_FILM);
ALTER TABLE SESSION ADD FOREIGN KEY(HALL) REFERENCES HALL(ID_HALL);
ALTER TABLE TICKET ADD FOREIGN KEY(SESSION) REFERENCES SESSION(ID_SESSION);
ALTER TABLE TICKET ADD FOREIGN KEY(SEAT) REFERENCES SEAT(ID_SEAT);
ALTER TABLE SEAT ADD FOREIGN KEY(HALL) REFERENCES HALL(ID_HALL);

INSERT INTO FILM(NAME, DURATION)
VALUES ('Побег из Шоушенка', 142),
('Зеленая миля', 189), 
('Форрест Гамп', 142 );

INSERT INTO SESSION(HALL, DATE, TIME, FILM)
VALUES (1,'2015-11-11', '17:00:00', 1),
(2, '2015-11-11', '19:00:00', 2), 
(3, '2015-12-11', '18:00:00', 3);

INSERT INTO HALL(NAME, RANGSE, SEATS)
VALUES ( 'Астра', 10, 100),
( 'Роза', 8, 80),
('Гиацинт ', 7, 70);

INSERT INTO GENRE
VALUES (1, 'Драма '),
(2, 'Драма '),
(2, 'Фэнтези '),
(3, 'Драма');

INSERT INTO SEAT( HALL, RANGE, SEAT)
VALUES (1, 1, 1),
(1, 1, 2),
(1, 1, 3);

INSERT INTO TICKET(SESSION, SEAT, PRICE )
VALUES (1, 1, 10.00),
(1, 2, 10.00),
(2, 1, 14.00);

SELECT * FROM FILM;
SELECT * FROM GENRE;
SELECT * FROM SESSION;
SELECT * FROM HALL;
SELECT * FROM SEAT;
SELECT * FROM TICKET;

CREATE TRIGGER TR1
ON SESSION
AFTER INSERT
AS
DECLARE @HALL INT
SELECT @HALL=HALL
FROM SESSION
WHERE ID_SESSION IN (
    SELECT MAX(ID_SESSION)
    FROM SESSION
)
DECLARE @ROW INT
SELECT @ROW=RANGSE
FROM HALL
WHERE ID_HALL IN (
    SELECT HALL
    FROM SESSION 
    WHERE ID_SESSION IN (SELECT MAX(ID_SESSION) FROM SESSION)
)
DECLARE @SEAT INT
SELECT @SEAT=SEATS
FROM HALL
WHERE ID_HALL IN (
    SELECT HALL
    FROM SESSION 
    WHERE ID_SESSION IN (SELECT MAX(ID_SESSION) FROM SESSION)
)
DECLARE @A INT 
SET @A=1
DECLARE @B INT
SET @B=1
BEGIN
WHILE @A<=@ROW
BEGIN
WHILE @B<=(@SEAT/@ROW)
BEGIN
INSERT INTO SEAT(HALL, RANGE, SEAT)
VALUES(@HALL, @A, @B)
SET @B=@B+1
END
SET @B=1
SET @A=@A+1
END
END;

INSERT INTO SESSION(HALL, DATE, TIME, FILM)
VALUES (1,'2016-10-11', '18:00:00', 2)

DROP TRIGGER TR1;

DELETE FROM SEAT
WHERE ID_SEAT>3;

CREATE TRIGGER TR2
ON HALL
AFTER INSERT
AS
DECLARE @HALL INT
SELECT @HALL=ID_HALL
FROM HALL
WHERE ID_HALL IN (SELECT MAX(ID_HALL) FROM HALL)
DECLARE @ROW INT
SELECT @ROW=RANGSE
FROM HALL
WHERE ID_HALL IN (SELECT MAX(ID_HALL) FROM HALL)
DECLARE @SEAT INT
SELECT @SEAT=SEATS
FROM HALL
WHERE ID_HALL IN (SELECT MAX(ID_HALL) FROM HALL)
DECLARE @A INT 
SET @A=1
DECLARE @B INT
SET @B=1
BEGIN
WHILE @A<=@ROW
BEGIN
WHILE @B<=(@SEAT/@ROW)
BEGIN
INSERT INTO SEAT(HALL, RANGE, SEAT)
VALUES(@HALL, @A, @B)
SET @B=@B+1
END
SET @B=1
SET @A=@A+1
END
END;


INSERT INTO HALL(NAME ,RANGSE ,SEATS)
VALUES ('Сакура', 11, 121);

DROP TRIGGER TR2;

DELETE FROM SEAT
WHERE ID_SEAT>3;

SET ANSI_NULLS ON
SET ANSI_NULLS OFF

SELECT *
FROM FILM
WHERE DURATION = NULL;


INSERT INTO FILM
VALUES (NULL, NULL);